### ISSUE TITLE
How to reference Lottie JSON?

### ISSUE THREAD

**Issue by IOIIOOIO** [michaelfitzhavey/lottie-player-vue#2]
I was wondering if it's possible to reference the Lottie .json file from the Lottie website?

eg:

`<lottie-player src="https://assets10.lottiefiles.com/packages/lf20_UDstUT.json" />`

**EDIT:**

I see it is actually working, but I get an error in the console that it expects an object, but received a string.

**Comment by Shaif821** [comment]
I'm getting the same error. Did you find a fix?

**Comment by IOIIOOIO** [comment]
@Shaif821 

It appears that the lottie player still works when you give it a URL - it's just an error that appears in the console.

**Comment by michaelfitzhavey** [comment]
Removed the dependency on `src` being a string in https://github.com/michaelfitzhavey/lottie-player-vue/commit/93f775d1d9720e4757c5ca7bed46f64aa0a5880b

This console error should no longer occur in version `0.0.13` or higher.
