### ISSUE TITLE
 Invalid prop: type check failed for prop "src". Expected Object, got String with value "https://assets7.lottiefiles.com/packages/lf20_HVT7Ak.json".

### ISSUE THREAD

**Issue by juanrdlo** [michaelfitzhavey/lottie-player-vue#4]
Error to prop src, 

![image](https://user-images.githubusercontent.com/48454427/80431012-eb845d80-88b5-11ea-93e4-a36fb14d39bb.png)

**Comment by michaelfitzhavey** [comment]
The source is expected to be JSON data, not a string as per the Readme. Closing this issue and adding accepting url's as src to the roadmap.
